language: node_js
node_js:
- '10'
addons:
  ssh_known_hosts: 207.154.227.133
install: npm install
before_install:
- openssl aes-256-cbc -K $encrypted_3b0bb8758082_key -iv $encrypted_3b0bb8758082_iv
  -in deploy_key.enc -out deploy_key -d

deploy:
  provider: script
  skip_cleanup: true
  script: deploy.sh
  on:
    branch: master
