language: node_js
node_js:
- '10'
addons:
  ssh_known_hosts: $SERVER_URL
install: npm install
before_install:
- openssl aes-256-cbc -K $encrypted_3b0bb8758082_key -iv $encrypted_3b0bb8758082_iv
  -in deploy_key.enc -out /tmp/deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_key
- ssh-add /tmp/deploy_key


deploy:
  provider: script
  skip_cleanup: true
  script: sh ./deploy.sh
  on:
    branch: master
